import assert from 'node:assert';
import { after, before, describe, it } from 'node:test';
import xior, { XiorError, XiorRequestConfig, isXiorError } from 'xior';
import xiorErrorRetryPlugin from 'xior/plugins/error-retry';

import { startServer } from '../server';

let close: Function;
const port = 7870;
const baseURL = `http://localhost:${port}`;
before(async () => {
  close = await startServer(port);
});

after(async () => {
  return close(1);
});

describe('xior error retry plugin tests', () => {
  const instance = xior.create({ baseURL });
  instance.plugins.use(
    xiorErrorRetryPlugin({
      retryInterval: 1000,
      retryTimes: 3,
    })
  );

  it('should retry when `GET` error until success', async () => {
    await instance.get('/reset-error');
    const { data } = await instance.get('/retry-error', { params: { count: 3 } });
    assert.strictEqual(data.count, 3);
    assert.strictEqual(data.errorCount, 3);
  });

  it('should throw error when finish retryTimes', async () => {
    await instance.get('/reset-error');
    let error: XiorError | undefined = undefined;
    try {
      await instance.get('/retry-error', {
        params: { count: 3 },
        retryTimes: 2,
        retryInterval(count: number) {
          return count * 200;
        },
        onRetry(config: any, error: any, count: any) {
          console.log(`RETRY LOG: ${config.method} ${config.url} ${count} retry`);
        },
      } as any);
    } catch (e) {
      if (isXiorError(e)) {
        error = e as XiorError;
      }
    }
    assert.strictEqual(typeof error !== 'undefined', true);
    assert.strictEqual(error?.response?.data.errorCount, 2);
    assert.strictEqual(error?.response?.data.count, 3);
  });

  it('No retry with `POST` method in default', async () => {
    await instance.post('/reset-error');
    let error: XiorError | undefined = undefined;
    try {
      await instance.post('/retry-error', { count: 1 });
    } catch (e) {
      if (isXiorError(e)) {
        error = e as XiorError;
      }
    }
    assert.strictEqual(typeof error !== 'undefined', true);
    assert.strictEqual(error?.response?.data.errorCount, 0);
    assert.strictEqual(error?.response?.data.count, 1);
  });

  it('should retry when `POST` error with `enableRetry: true` until success', async () => {
    await instance.get('/reset-error');
    const { data } = await instance.post('/retry-error', { count: 3 }, {
      enableRetry: true,
      headers: {},
    } as any);
    assert.strictEqual(data.count, 3);
    assert.strictEqual(data.errorCount, 3);
  });

  it('should retry when `POST` error with `isGet: true` until success', async () => {
    await instance.get('/reset-error');
    const { data } = await instance.post(
      '/retry-error',
      { count: 3 },
      {
        isGet: true,
      }
    );
    assert.strictEqual(data.count, 3);
    assert.strictEqual(data.errorCount, 3);
  });

  it('should throw error when run out `retryTimes: 2` when `POST` error with `enableRetry: true`', async () => {
    const instance = xior.create({ baseURL });
    instance.plugins.use(
      xiorErrorRetryPlugin({
        retryInterval: 1000,
      })
    );
    await instance.get('/reset-error');
    let error: XiorError | undefined = undefined;
    try {
      await instance.post('/retry-error', { count: 3 }, {
        // retryTimes: 2,
        enableRetry: true,
      } as any);
    } catch (e) {
      if (isXiorError(e)) {
        error = e as XiorError;
      }
    }
    assert.strictEqual(typeof error !== 'undefined', true);
    assert.strictEqual(error?.response?.data.errorCount, 2);
    assert.strictEqual(error?.response?.data.count, 3);
  });

  it("should use the latest request inteceptor's request config when error retry", async () => {
    await xior.get('/reset-error', { baseURL });

    const instance = xior.create({ baseURL });

    let S = '';
    let errorCount = 0;

    instance.interceptors.request.use((config) => {
      if (S) {
        config.headers['S'] = S;
      }
      return config;
    });

    instance.interceptors.response.use(
      (config) => {
        return config;
      },
      (e) => {
        errorCount++;
        if (!S) {
          S = 'S123456';
        }
        throw e;
      }
    );

    instance.plugins.use(
      xiorErrorRetryPlugin({
        retryInterval: (count) => count * 500,
        onRetry(config, error, count) {
          console.log(`${config.method} ${config.url} retry ${count} times`);
        },
      })
    );
    let error: XiorError | undefined = undefined;
    let msg = '';
    try {
      const { data } = await instance.post('/retry-error', { count: 3 }, {
        retryTimes: 3,
        enableRetry: true,
      } as any);
      msg = data.msg;
    } catch (e) {
      if (isXiorError(e)) {
        error = e as XiorError;
      }
    }
    assert.strictEqual(errorCount, 1);
    assert.strictEqual(msg, 'ok');
    assert.strictEqual(typeof error === 'undefined', true);
  });

  it('shouldn\t error retry with `enableRetry: config `', async () => {
    const instance = xior.create({ baseURL });
    instance.plugins.use(
      xiorErrorRetryPlugin({
        retryInterval: 1000,
      })
    );
    await instance.get('/reset-error');
    let error: XiorError | undefined = undefined;
    try {
      await instance.post('/retry-error-401', { count: 3 }, {
        // retryTimes: 2,
        enableRetry: (config: XiorRequestConfig, error: XiorError) => {
          if (error.response?.status === 401) return false;
          return true;
        },
      } as any);
    } catch (e) {
      if (isXiorError(e)) {
        error = e as XiorError;
      }
    }
    assert.strictEqual(typeof error !== 'undefined', true);
    assert.strictEqual(error?.response?.data.errorCount, 0);
    assert.strictEqual(error?.response?.data.count, 3);
  });
});
